<?php


namespace Tofaha\Helper\Facades;


use Illuminate\Support\Facades\Facade;

class Table extends  Facade
{
    protected static function getFacadeAccessor()
    {
        return 'table'; // TODO: Change the autogenerated stub
    }

}
